{{ if .Values.ingress.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.auth.secret }}
data:
  auth: {{ htpasswd .Values.ingress.auth.username .Values.ingress.auth.password | b64enc | quote }}
{{ end }}